Repository ms-club-sliit/msclub-admin-panel, pull requests merged in 2021-12, with the labels that each got.

#10 Dockerfile Added
  Dockerfile
Labels: enhancement, feature

#9 README file updated
  README.md
Labels: documentation

#11 Feature/header footer
  package.json
  public/images/ms_club_logo_light.png
  src/App.scss
  src/components/footer/index.tsx
  src/components/index.ts
  src/components/navbar/index.tsx
  src/constants/index.ts
  src/index.scss
  src/pages/event/index.tsx
  src/pages/event/list/index.tsx
  src/routes/app-routes.tsx
  src/store/event-store/IEvent.ts
  src/styles/breakpoints.scss
  src/styles/colors.scss
  src/styles/events.scss
  src/styles/index.scss
  src/styles/navbar.scss
  src/styles/table.scss
  yarn.lock
Labels: feature, ui, redux

#14 Add Insert Form
  src/components/insert-form/index.tsx
  src/pages/event/list/index.tsx
Labels: feature

#18 Feature/workflow setup development
  .github/workflows/development.yml
Labels: enhancement

#17 Feature/workflow setup production
  .github/workflows/production.yml
Labels: enhancement

#21 Event service get and insert UIs
  package.json
  public/index.html
  src/App.scss
  src/App.tsx
  src/components/image-canvas/index.tsx
  src/components/insert-form/index.tsx
  src/components/navbar/index.tsx
  src/constants/index.ts
  src/interfaces/IEvent.ts
  src/interfaces/index.ts
  src/pages/event/add/index.tsx
  src/pages/event/list/index.tsx
  src/pages/event/view/index.tsx
  src/store/api/EventAPI.ts
  src/store/api/config.ts
  src/store/event-store/IEvent.ts
  src/store/event-store/eventActionTypes.ts
  src/store/event-store/eventActions.ts
  src/store/event-store/eventReducer.ts
  src/store/interfaces/index.ts
  src/styles/events.scss
  src/styles/image-canvas.scss
  src/styles/table.scss
  yarn.lock
Labels: enhancement, feature, ui, redux

#26 Feature/login
  .gitignore
  package-lock.json
  package.json
  public/images/ms_club_logo_crop.png
  src/App.scss
  src/App.test.tsx
  src/App.tsx
  src/components/navbar/index.tsx
  src/constants/index.ts
  src/pages/event/add/index.tsx
  src/pages/event/list/delete.tsx
  src/pages/event/list/index.tsx
  src/pages/index.ts
  src/pages/login/index.tsx
  src/pages/login/interfaces/index.ts
  src/routes/PrivateRoute.tsx
  src/routes/app-routes.tsx
  src/routes/index.tsx
  src/store/api/UserAPI.ts
  src/store/event-store/eventReducer.ts
  src/store/user-store/IUser.ts
  src/store/user-store/userActionTypes.ts
  src/store/user-store/userActions.ts
  src/store/user-store/userReducer.ts
  src/styles/login.scss
  yarn.lock
Labels: enhancement, feature, redux, high-priority

#42 feature/application-store added
  src/store/application-store/applicationActionTypes.ts
  src/store/application-store/applicationActions.ts
  src/store/application-store/applicationReducer.ts
  src/store/interfaces/IApplication.ts
Labels: feature

#51 Feature ITopSpeaker interface
  src/interfaces/ITopSpeaker.ts
  src/interfaces/index.ts
Labels: feature

#53 Implemented ApplicationAPI
  src/store/api/ApplicationAPI.ts
  src/store/application-store/applicationActions.ts
Labels: feature

#52 Feature/top speaker actions and api
  package-lock.json
  src/store/api/TopSpeakerAPI.ts
  src/store/top-speaker-store/ITopSpeaker.ts
  src/store/top-speaker-store/topSpeakerActions.ts
  yarn.lock
Labels: feature

#54 Fix/interface issue
  src/interfaces/IApplication.ts
  src/interfaces/IEvent.ts
  src/interfaces/ITopSpeaker.ts
  src/interfaces/IUser.ts
  src/interfaces/IWebinar.ts
  src/interfaces/index.ts
  src/pages/event/add/index.tsx
  src/pages/event/delete/index.tsx
  src/pages/event/interfaces/index.ts
  src/pages/event/list/delete.tsx
  src/pages/event/list/index.tsx
  src/pages/event/update/index.tsx
  src/pages/event/view/index.tsx
  src/store/api/ApplicationAPI.ts
  src/store/api/EventAPI.ts
  src/store/api/TopSpeakerAPI.ts
  src/store/api/UserAPI.ts
  src/store/api/WebinarAPI.ts
  src/store/application-store/applicationReducer.ts
  src/store/event-store/IEvent.ts
  src/store/event-store/eventReducer.ts
  src/store/index.ts
  src/store/interfaces/IApplication.ts
  src/store/interfaces/index.ts
  src/store/top-speaker-store/ITopSpeaker.ts
  src/store/user-store/userActions.ts
  src/store/user-store/userReducer.ts
  src/store/webinar-store/IWebinar.ts
  src/store/webinar-store/webinarActions.ts
  yarn.lock
Labels: high-priority, fix
