Repository ms-club-sliit/msclub-admin-panel, pull requests merged in 2022-02, with the labels that each got.

#137 Implemented top speaker list, deleted list and view page.
  src/App.scss
  src/constants/index.ts
  src/pages/index.ts
  src/pages/top-speaker/index.tsx
  src/pages/top-speaker/list/index.tsx
  src/pages/top-speaker/view/index.tsx
  src/routes/index.tsx
  src/styles/top-speakers.scss
Labels: feature

#141 Add top speaker
  src/interfaces/ITopSpeaker.ts
  src/interfaces/index.ts
  src/pages/top-speaker/add/index.tsx
  src/pages/top-speaker/list/index.tsx
  src/pages/top-speaker/view/index.tsx
  src/routes/index.tsx
  src/styles/top-speakers.scss
Labels: feature

#144 display recent messages in the dashboard completed
  src/pages/dashboard/dashboardComponenets/recentMessage.tsx
  src/styles/dashboardComponenets/recentMessages.scss
Labels: feature

#145 Feature/deleted application list
  src/interfaces/IApplication.ts
  src/pages/application/delete/index.tsx
  src/pages/application/list/delete.tsx
  src/pages/application/list/index.tsx
  src/pages/dashboard/dashboardComponenets/recentMessage.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/store/api/ApplicationAPI.ts
  src/store/application-store/applicationActions.ts
  src/store/application-store/applicationReducer.ts
  src/store/index.ts
  yarn.lock
Labels: bug, feature

#147 Get data in dashboard from backend
  src/interfaces/IChart.ts
  src/pages/dashboard/dashboardComponenets/chart.tsx
  src/pages/dashboard/dashboardComponenets/mainCard.tsx
  src/pages/dashboard/dashboardComponenets/studentApplication.tsx
Labels: enhancement, feature

#151 Settings page update and delete operations
  .eslintrc
  .gitignore
  package-lock.json
  package.json
  src/App.scss
  src/interfaces/IOrganization.ts
  src/interfaces/IUser.ts
  src/interfaces/index.ts
  src/pages/event/list/index.tsx
  src/pages/index.ts
  src/pages/settings/index.tsx
  src/pages/settings/organization/index.tsx
  src/pages/settings/users/add/index.tsx
  src/pages/settings/users/delete/index.tsx
  src/pages/settings/users/index.tsx
  src/pages/settings/users/list/index.tsx
  src/pages/settings/users/view/index.tsx
  src/pages/top-speaker/list/index.tsx
  src/routes/index.tsx
  src/store/api/OrganizationAPI.ts
  src/store/api/UserAPI.ts
  src/store/organization-store/organizationActionTypes.ts
  src/store/organization-store/organizationActions.ts
  src/store/organization-store/organizationReducer.ts
  src/store/reducer.ts
  src/store/user-store/userActionTypes.ts
  src/store/user-store/userActions.ts
  src/store/user-store/userReducer.ts
  src/styles/colors.scss
  src/styles/settings.scss
Labels: enhancement, feature

#153 Implemented edit Top speaker function
  src/interfaces/IChart.ts
  src/pages/top-speaker/list/index.tsx
  src/pages/top-speaker/update/index.tsx
Labels: feature

#165 Bug - Remove the view button in application list view
  src/pages/application/list/index.tsx
Labels: bug

#168 Implement the Event Permanently delete
  src/pages/event/list/delete.tsx
  src/pages/event/permanent-delete/index.tsx
  src/store/api/EventAPI.ts
  src/store/event-store/eventActions.ts
Labels: enhancement, feature

#173 Recovered Deleted Applications
  src/pages/application/list/delete.tsx
  src/pages/application/recover-delete/index.tsx
  src/store/api/ApplicationAPI.ts
  src/store/application-store/applicationActions.ts
Labels: feature

#176 Implement permanent delete for inquiry
  src/pages/inquiry/list/delete.tsx
  src/pages/inquiry/permanent-delete/index.tsx
  src/store/api/InquiryAPI.ts
  src/store/inquiry-store/inquiryAction.ts
Labels: feature

#177 Recovery deleted webinar
  src/pages/webinar/list/delete.tsx
  src/pages/webinar/recover-delete/index.tsx
  src/store/api/WebinarAPI.ts
  src/store/webinar-store/webinarActions.ts
Labels: enhancement, feature

#178 implemented recover deleted top speaker and delete top speaker
  src/pages/top-speaker/delete/index.tsx
  src/pages/top-speaker/list/delete.tsx
  src/pages/top-speaker/list/index.tsx
  src/pages/top-speaker/recover-delete/index.tsx
  src/store/api/TopSpeakerAPI.ts
  src/store/top-speaker-store/topSpeakerActions.ts
Labels: feature

#184 Implemented to display delete and edit buttons only for ADMIN and ROOT ADMIN
  src/pages/event/list/index.tsx
  src/pages/settings/users/view/index.tsx
  src/pages/top-speaker/delete/index.tsx
  src/pages/top-speaker/list/delete.tsx
  src/pages/top-speaker/list/index.tsx
  src/store/api/TopSpeakerAPI.ts
  src/store/top-speaker-store/topSpeakerActions.ts
Labels: enhancement, feature, fix
