Repository ms-club-sliit/msclub-admin-panel, pull requests merged in 2022-01, with the labels that each got.

#55 Feature/top speaker reducer
  src/interfaces/ITopSpeaker.ts
  src/interfaces/index.ts
  src/store/top-speaker-store/topSpeakerActionTypes.ts
  src/store/top-speaker-store/topSpeakerReducer.ts
Labels: feature

#56 Create webinar reducer added #30
  src/store/webinar-store/webinarActionTypes.ts
  src/store/webinar-store/webinarReducer.ts
Labels: feature

#71 Contact Us Reducer Implemented
  src/store/contact-store/contactUsReducer.ts
Labels: feature, high-priority

#73 Implement contactus actions
  src/store/api/ContactUsAPI.ts
  src/store/contact-store/contactUsAction.ts
Labels: feature

#80 List view to display all the available applications
  src/pages/application/list/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: enhancement, feature

#82 Fix/eslint build fail issie
  package.json
  yarn.lock
Labels: bug, high-priority, fix

#91 Implemented - All the Available Webinars in the Table
  package.json
  src/pages/index.ts
  src/pages/webinar/index.tsx
  src/pages/webinar/list/index.tsx
  src/routes/index.tsx
  src/store/reducer.ts
  src/store/webinar-store/webinarReducer.ts
  yarn.lock
Labels: feature

#97 Implemented Teams meeting schedule feature
  package.json
  src/interfaces/IInterview.ts
  src/pages/application/interview/index.tsx
  yarn.lock
Labels: enhancement, feature

#112 Minor change in eslint
  .eslintrc
  src/pages/application/list/delete.tsx
Labels: bug

#113 Fixed webinar form issue
  src/components/image-canvas/index.tsx
  src/interfaces/IWebinar.ts
  src/pages/webinar/add/index.tsx
  src/store/webinar-store/webinarReducer.ts
Labels: bug

#117 Delete appication implemented
  src/pages/application/list/index.tsx
  src/store/api/ApplicationAPI.ts
Labels: feature

#108 Implement contactUs view page
  src/pages/index.ts
  src/pages/inquiry/index.tsx
  src/pages/inquiry/list/index.tsx
  src/routes/index.tsx
  src/store/api/ContactUsAPI.ts
  src/store/contact-store/contactUsAction.ts
  src/store/contact-store/contactUsReducer.ts
  src/store/reducer.ts
Labels: feature

#124 Created TopSpeakerList.ts and TopSpeaker delete.tsx
  src/interfaces/ITopSpeaker.ts
  src/pages/top-speaker/list/delete.tsx
  src/pages/top-speaker/list/index.tsx
  src/store/top-speaker-store/topSpeakerActions.ts
Labels: enhancement, feature

#126 Feature/speaker list
  package-lock.json
  src/pages/top-speaker/list/index.tsx
  src/store/reducer.ts
Labels: enhancement, feature

#128 Created Dashboard UI
  package-lock.json
  package.json
  src/App.scss
  src/interfaces/ITopSpeaker.ts
  src/pages/dashboard/dashboardComponenets/chart.tsx
  src/pages/dashboard/dashboardComponenets/dateTime.tsx
  src/pages/dashboard/dashboardComponenets/mainCard.tsx
  src/pages/dashboard/dashboardComponenets/recentLogin.tsx
  src/pages/dashboard/dashboardComponenets/recentMessage.tsx
  src/pages/dashboard/dashboardComponenets/studentApplication.tsx
  src/pages/dashboard/index.tsx
  src/pages/index.ts
  src/pages/top-speaker/list/delete.tsx
  src/pages/top-speaker/list/index.tsx
  src/routes/index.tsx
  src/store/reducer.ts
  src/store/top-speaker-store/topSpeakerActions.ts
  src/styles/dashboardComponenets/chart.scss
  src/styles/dashboardComponenets/dateTime.scss
  src/styles/dashboardComponenets/mainCard.scss
  src/styles/dashboardComponenets/recentLogins.scss
  src/styles/dashboardComponenets/recentMessages.scss
  src/styles/dashboardComponenets/studentApplication.scss
  yarn.lock
Labels: feature, high-priority

#132 Fix the bug in inquires
  src/pages/inquiry/delete/index.tsx
  src/pages/inquiry/list/index.tsx
  src/store/inquiry-store/inquiryAction.ts
  src/store/inquiry-store/inquiryReducer.ts
Labels: bug

#135 top-speaker-list display bug fixed
  src/pages/index.ts
  src/routes/index.tsx
Labels: bug
