Repository ms-club-sliit/msclub-admin-panel, pull requests merged in 2022-05, with the labels that each got.

#267 Added URLs to MS-Scheduler Card
  .github/workflows/development.yml
  .github/workflows/production.yml
  src/pages/dashboard/meeting_scheduler/index.tsx
Labels: enhancement

#268 Feature/get interview meeting details
  src/interfaces/IApplication.ts
  src/locales/en-US/translation.json
  src/pages/application/list/index.tsx
  src/pages/application/view-interview-details/index.tsx
Labels: feature

#271 Fix the Recent Login bug
  .gitignore
  package-lock.json
  src/interfaces/ILogins.ts
  src/pages/dashboard/login_info/index.tsx
  src/store/logins-store/loginsReducer.ts
Labels: bug
