Repository ms-club-sliit/msclub-admin-panel, pull requests merged in 2022-04, with the labels that each got.

#237 Logout Button bug fixed
  src/styles/navbar.scss
Labels: fix

#239 Fix recent application application name bug
  src/pages/dashboard/application_info/index.tsx
  src/pages/dashboard/login_info/index.tsx
Labels: fix

#243 Reply inquiries feature implemented ✅
  src/interfaces/IInquiry.ts
  src/interfaces/index.ts
  src/locales/en-US/translation.json
  src/pages/inquiry/list/index.tsx
  src/pages/inquiry/reply/index.tsx
  src/store/api/InquiryAPI.ts
  src/store/inquiry-store/inquiryAction.ts
  src/store/inquiry-store/inquiryActionTypes.ts
  src/store/inquiry-store/inquiryReducer.ts
Labels: feature, high-priority

#249 Changed the space between the text and the line
  src/styles/dashboard.scss
Labels: fix

#254 MS Short image - fix css issue in firefox browser
  src/styles/dashboard.scss
Labels: bug, fix

#251 Show Replies For Inquries when expanding
  src/locales/en-US/translation.json
  src/pages/inquiry/list/index.tsx
Labels: enhancement, feature

#253 Aligned text to the left in RecentLogin component
  src/styles/dashboard.scss
Labels: fix

#258 Added the Meeting Scheduler Card
  public/images/meetingscheduler.svg
  src/locales/en-US/translation.json
  src/pages/dashboard/index.tsx
  src/pages/dashboard/meeting_scheduler/index.tsx
Labels: feature

#260 Fixed bug and implemented Organization Edit
  src/interfaces/IOrganization.ts
  src/interfaces/index.ts
  src/pages/settings/organization/index.tsx
  src/store/api/OrganizationAPI.ts
Labels: bug, feature

#259 Bug Fixed - Edited image preview in ImageCanvas in current session
  src/pages/event/update/index.tsx
  src/pages/webinar/update/index.tsx
Labels: bug
