Repository ms-club-sliit/msclub-admin-panel, pull requests merged in 2022-03, with the labels that each got.

#185 Feature/delete permenently top speaker
  src/pages/top-speaker/list/delete.tsx
  src/pages/top-speaker/permenent-delete/index.tsx
  src/store/api/TopSpeakerAPI.ts
  src/store/top-speaker-store/topSpeakerActions.ts
Labels: enhancement, feature

#191 Bug fixed
  src/pages/top-speaker/list/index.tsx
Labels: fix

#197 Feature/delete permanently topspeaker
  src/pages/top-speaker/list/delete.tsx
Labels: bug

#194 Implemented inquires to display delete and edit buttons only for ADMIN and ROOT ADMIN
  src/pages/inquiry/list/index.tsx
Labels: enhancement, feature

#207 Feature/event recover and delete permanent button auth
  src/pages/event/list/delete.tsx
Labels: enhancement, feature, high-priority

#209 New UI for Dashboard (Dashboard V2)
  package.json
  public/images/dashboard.png
  public/images/profile.png
  src/App.scss
  src/pages/application/list/delete.tsx
  src/pages/application/list/index.tsx
  src/pages/application/loader/index.tsx
  src/pages/dashboard/application_info/index.tsx
  src/pages/dashboard/application_status/index.tsx
  src/pages/dashboard/dashboardComponenets/chart.tsx
  src/pages/dashboard/dashboardComponenets/dateTime.tsx
  src/pages/dashboard/dashboardComponenets/mainCard.tsx
  src/pages/dashboard/dashboardComponenets/recentApplications.tsx
  src/pages/dashboard/dashboardComponenets/recentLogin.tsx
  src/pages/dashboard/dashboardComponenets/recentMessage.tsx
  src/pages/dashboard/dashboardComponenets/studentApplication.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/loader/index.tsx
  src/pages/dashboard/login_info/index.tsx
  src/pages/dashboard/overview/index.tsx
  src/pages/event/list/index.tsx
  src/pages/event/loader/index.tsx
  src/pages/inquiry/list/index.tsx
  src/pages/inquiry/loader/index.tsx
  src/pages/top-speaker/list/index.tsx
  src/pages/top-speaker/loader/index.tsx
  src/pages/webinar/list/index.tsx
  src/pages/webinar/loader/index.tsx
  src/store/index.ts
  src/styles/dashboard.scss
  src/styles/dashboardComponenets/chart.scss
  src/styles/dashboardComponenets/dateTime.scss
  src/styles/dashboardComponenets/mainCard.scss
  src/styles/dashboardComponenets/recentLogins.scss
  src/styles/dashboardComponenets/recentMessages.scss
  src/styles/dashboardComponenets/studentApplication.scss
  yarn.lock
Labels: enhancement, ui, high-priority

#210 recover and delete permenent buttons displayed for admin and root admin
  src/pages/webinar/list/delete.tsx
Labels: feature, high-priority

#223 Top Speaker - Recover and Delete permanently buttons display only for ADMIN and ROOT ADMIN
  src/pages/top-speaker/list/delete.tsx
Labels: feature, high-priority

#224 Webinar - Delete and Edit buttons display only for ADMIN, ROOT ADMIN and EDITOR
  src/pages/webinar/list/index.tsx
Labels: enhancement, feature

#226 Fixed the bug of created date and time in Inquiries table
  src/pages/inquiry/list/index.tsx
Labels: bug

#227 Fix Dashboard view for unauthorized user
  src/routes/index.tsx
Labels: bug

#230 Implemented Face authentication
  package.json
  src/interfaces/ILoginFaceAuthentication.ts
  src/interfaces/index.ts
  src/pages/index.ts
  src/pages/login-face-authentication/index.tsx
  src/pages/login/index.tsx
  src/routes/index.tsx
  src/store/api/UserAPI.ts
  src/store/user-store/userActions.ts
  yarn.lock
Labels: enhancement, feature

#234 Feature/translation for all pages
  src/components/footer/index.tsx
  src/components/navbar/index.tsx
  src/locales/en-US/translation.json
  src/pages/application/delete/index.tsx
  src/pages/application/interview/index.tsx
  src/pages/application/list/delete.tsx
  src/pages/application/list/index.tsx
  src/pages/application/permanent-delete/index.tsx
  src/pages/application/recover-delete/index.tsx
  src/pages/dashboard/application_info/index.tsx
  src/pages/dashboard/application_status/index.tsx
  src/pages/dashboard/msshort/index.tsx
  src/pages/event/add/index.tsx
  src/pages/event/delete/index.tsx
  src/pages/event/list/delete.tsx
  src/pages/event/list/index.tsx
  src/pages/event/permanent-delete/index.tsx
  src/pages/event/recover-delete/index.tsx
  src/pages/event/update/index.tsx
  src/pages/event/view/index.tsx
  src/pages/inquiry/delete/index.tsx
  src/pages/inquiry/list/delete.tsx
  src/pages/inquiry/list/index.tsx
  src/pages/inquiry/permanent-delete/index.tsx
  src/pages/inquiry/recover-delete/index.tsx
  src/pages/login-face-authentication/index.tsx
  src/pages/login/index.tsx
  src/pages/settings/index.tsx
  src/pages/settings/organization/index.tsx
  src/pages/top-speaker/add/index.tsx
  src/pages/top-speaker/delete/index.tsx
  src/pages/top-speaker/list/delete.tsx
  src/pages/top-speaker/list/index.tsx
  src/pages/top-speaker/permenent-delete/index.tsx
  src/pages/top-speaker/recover-delete/index.tsx
  src/pages/top-speaker/update/index.tsx
  src/pages/top-speaker/view/index.tsx
  src/pages/webinar/add/index.tsx
  src/pages/webinar/delete/index.tsx
  src/pages/webinar/list/delete.tsx
  src/pages/webinar/list/index.tsx
  src/pages/webinar/permanent-delete/index.tsx
  src/pages/webinar/recover-delete/index.tsx
  src/pages/webinar/update/index.tsx
  src/pages/webinar/view/index.tsx
Labels: feature
